version: '3.7'

services:
  mongodb:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - "/var/lib/direct-http-agent/mongodb:/data/db"
  agent:
    build: .
    init: true
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - "/etc/direct-http-agent/agent:/etc/agent"
      - "/var/lib/direct-http-agent/storage.local:/data/storage.local"
