version: '3.7'

services:
  mongodb:
    volumes:
      - "./data/mongodb:/data/db"
  agent:
    environment:
      NODE_ENV: development
    volumes:
      - "./etc/agent:/etc/agent"
      - "./data/storage.local:/data/storage.local"
