version: '3'

services:
  mongodb:
    volumes:
      - "/var/lib/direct-http-agent/mongodb:/data/db"
  agent:
    environment:
      NODE_ENV: production
    volumes:
      - "/etc/direct-http-agent/agent:/etc/agent"
      - "/var/lib/direct-http-agent/storage.local:/data/storage.local"